version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: usuario       # O usuário do PostgreSQL
      POSTGRES_PASSWORD: senha     # A senha para o usuário
      POSTGRES_DB: produtos_db    # O nome do banco de dados a ser criado
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Persistência de dados do banco de dados
    ports:
      - "5432:5432"               # Mapeia a porta 5432 do PostgreSQL para a porta 5432 do host
    networks:
      - db_network

volumes:
  postgres_data:
    driver: local

networks:
  db_network:
    driver: bridge
