version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: usuario     
      POSTGRES_PASSWORD: senha     
      POSTGRES_DB: produtos_db    
    volumes:
      - postgres_data:/var/lib/postgresql/data   
    ports:
      - "5432:5432"             
    networks:
      - db_network

volumes:
  postgres_data:
    driver: local

networks:
  db_network:
    driver: bridge
